services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: qbank-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: qbank
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/qbank --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - qbank-network

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: qbank-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - qbank-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qbank-backend
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./extracted_text:/app/extracted_text
      - ./generated_questions:/app/generated_questions
      - ./models:/app/models
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=qbank
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - LLM_PROVIDER=ollama
      - MODEL_NAME=llama3
      - OLLAMA_BASE_URL=http://ollama:11434
      - MLX_MAX_TOKENS=2048
      - MLX_TEMPERATURE=0.7
    depends_on:
      mongodb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - qbank-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qbank-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - mongodb
    networks:
      - qbank-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ollama_data:
    driver: local

networks:
  qbank-network:
    driver: bridge
